version: '3.8'

services:
  auth-service:
    build:
      context: .
      network: host
    container_name: auth-service
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./:/app